### ISSUE TITLE
x11-libs/gtk+ gnome-base/libglade dependencies

### ISSUE THREAD

**Issue by bober2000** [homoludens/canoncapt-euilds#2]
net-print/cndrvcups-capt need >=x11-libs/gtk+-2.0 >=gnome-base/libglade-2.0.0  as dependencies

**Comment by bober2000** [comment]
Cant add patch here so:

diff --git a/net-print/cndrvcups-common/cndrvcups-common-2.60-r1.ebuild b/net-print/cndrvcups-common/cndrvcups-common-2.60-r1.ebuild
index aeb7499..760694b 100644
--- a/net-print/cndrvcups-common/cndrvcups-common-2.60-r1.ebuild
+++ b/net-print/cndrvcups-common/cndrvcups-common-2.60-r1.ebuild
@@ -19,7 +19,9 @@ KEYWORDS="~amd64 ~x86"
 IUSE="-cngplp"    # enable or disable cngplp compilation, may cause build break on ~amd64, don't really know if cngplp is ever needed
 RESTRICT=""

-DEPEND=">=net-print/cups-1.1.17"
+DEPEND=">=net-print/cups-1.1.17
-   >=x11-libs/gtk+-2.0.0
- > =gnome-base/libglade-2.0.0"
  > S=${WORKDIR}/${PN}-$(get_version_component_range 1-2)
  
  dir=/usr/$(get_libdir)

**Comment by bober2000** [comment]
Or as file https://www.dropbox.com/s/gzb1ukox4vawq0w/issue-2.patch?dl=0

**Comment by homoludens** [comment]
Thank you, I have updated ebuilds.

I would like to find a way to have this drivers without any X dependencies. It is frustrating to need X and gtk to be able to install drivers. And some people would like to have headless printer server.
